"""Tables and figure for `revision.local_global_continuum`.

    python -m revision.local_global_continuum --report
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from revision.paper_stats import DATASETS  # noqa: E402
from utils.metrics import paired_wilcoxon  # noqa: E402

LG = REPO.parent / "results" / "local_global"
NAME = {"folktables_income_CA_2018": "folktables", "wyodot_kvdw_labeled": "wyodot",
        "breast_cancer": "breast cancer", "uci_credit": "uci credit", "uci_adult": "uci adult"}
nm = lambda d: NAME.get(d, d)  # noqa: E731
KLAB = lambda k: "∞" if k is None else str(k)  # noqa: E731


def f3(x):
    return "—" if x is None or not np.isfinite(x) else f"{x:.3f}"


def table(h, rows):
    return "\n".join(["| " + " | ".join(h) + " |", "|---" + "|---:" * (len(h) - 1) + "|"] +
                     ["| " + " | ".join(r) + " |" for r in rows]) + "\n"


def main() -> int:
    R = json.loads((LG / "continuum.json").read_text())
    seeds = sorted({r["seed"] for r in R})
    # (arm, ds) -> setting -> list over seeds
    pts = defaultdict(lambda: defaultdict(list))
    loc = defaultdict(lambda: defaultdict(list))
    paper = defaultdict(list)
    for r in R:
        for p in r["points"]:
            pts[(r["arm"], r["dataset"])][(p["starts"], p["tau"], p["k"])].append(p)
        for m, v in r["local"].items():
            loc[(r["arm"], r["dataset"])][m].append(v)
        paper[(r["arm"], r["dataset"])].append(r["class_paper"])

    def dsv(arm, setting, q):
        out = {}
        for ds in DATASETS:
            v = [p[q] for p in pts[(arm, ds)].get(setting, []) if p[q] is not None]
            out[ds] = float(np.mean(v)) if v else float("nan")
        return out

    def mean(d):
        v = [x for x in d.values() if np.isfinite(x)]
        return float(np.mean(v)) if v else float("nan")

    parts = [
        "# One set of policies, from local to global explanations\n",
        f"Generated by `python -m revision.local_global_continuum --report`. Seeds {', '.join(map(str, seeds))}, 12 datasets, the paper's "
        "emp τ_C = 0.10 RLDA / MADA policies — **no retraining**. An explanation is always the box from one rollout of the class policy "
        "started at a point (containment on). Three selection parameters move the method: **starts** (rollouts per class, started at "
        "D_train rows of that class; the local case is one rollout at the input being explained), **k** (boxes kept per class) and "
        "**τ** (a box is admissible only if its D_val Fid ≥ τ). Boxes are chosen greedily on D_val by new class rows covered; the set "
        "is read as a classifier on D_test (conflicts → best D_val union Fid, no box → abstain). 'Tree, same size' = the plain global "
        "surrogate with as many leaves as the rule set has boxes (coverage 1). Means over datasets of seed means.\n",
    ]

    for arm in ("rlda", "mada"):
        A = arm.upper()
        rows = []
        # local end
        L = {m: {q: mean({ds: np.mean([v[q] for v in loc[(arm, ds)][m]]) if loc[(arm, ds)][m] else np.nan for ds in DATASETS})
                 for q in ("emp_fid", "pert_precision", "coverage", "cond")} for m in ("policy", "anchors", "tree_d3_leaf")}
        rows.append(["**Local** — one box per input (start = x*, k = 1)", f3(L["policy"]["emp_fid"]), f"{f3(L['policy']['coverage'])} per box",
                     "—", "1 per input", f"{L['policy']['cond']:.1f}", f"Anchors {f3(L['anchors']['emp_fid'])} (cov {f3(L['anchors']['coverage'])}); "
                     f"tree d3 leaf {f3(L['tree_d3_leaf']['emp_fid'])} (cov {f3(L['tree_d3_leaf']['coverage'])})"])
        settings = [(1, 0.9, 1), (10, 0.9, 1), (300, 0.9, 1), (300, 0.9, 5), (300, 0.9, None), (300, 0.8, None), (300, 0.0, 5), (300, 0.0, None)]
        for st in settings:
            if st == (300, 0.9, 5):
                P = {q: mean({ds: np.mean([p[q] for p in paper[(arm, ds)] if p[q] is not None]) for ds in DATASETS})
                     for q in ("fid", "coverage", "eff", "n_rules", "cond_per_rule", "tree_same_size_fid")}
                rows.append(["*Paper's class rule sets (class-mode pool, k = 1)*", f3(P["fid"]), f3(P["coverage"]), f3(P["eff"]),
                             f"{P['n_rules']:.1f}", f"{P['cond_per_rule']:.1f}", f3(P["tree_same_size_fid"])])
            v = {q: mean(dsv(arm, st, q)) for q in ("fid", "coverage", "eff", "n_rules", "cond_per_rule", "tree_same_size_fid")}
            tag = "**Global**" if st == (300, 0.0, None) else ""
            rows.append([f"{tag} starts {st[0]}, τ {st[1]:.2f}, k {KLAB(st[2])}".strip(), f3(v["fid"]), f3(v["coverage"]), f3(v["eff"]),
                         f"{v['n_rules']:.1f}", f"{v['cond_per_rule']:.1f}", f3(v["tree_same_size_fid"])])
        parts.append(f"## {A}: the path from local to global\n")
        parts.append(table(["Setting", "Fid (decided rows)", "Coverage", "Eff", "Boxes", "Conditions / box", "Tree, same size: Fid (cov 1)"], rows))

        # grid
        parts.append(f"**{A}, full grid: coverage / Fid** (rows: starts per class; columns: k)\n")
        for tau in (0.9, 0.0):
            grid = []
            for N in (1, 3, 10, 30, 100, 300):
                grid.append([str(N)] + [f"{f3(mean(dsv(arm, (N, tau, k), 'coverage')))} / {f3(mean(dsv(arm, (N, tau, k), 'fid')))}"
                                        for k in (1, 2, 5, 10, 20, 50, None)])
            parts.append(f"τ = {tau:.2f}\n")
            parts.append(table(["starts \\ k"] + [KLAB(k) for k in (1, 2, 5, 10, 20, 50, None)], grid))

        # dataset-wise at the two global settings and the paper setting
        rows = []
        for ds in DATASETS:
            r = [nm(ds)]
            pp = paper[(arm, ds)]
            r.append(f"{f3(np.mean([p['fid'] for p in pp]))} / {f3(np.mean([p['coverage'] for p in pp]))}")
            for st in ((300, 0.9, None), (300, 0.0, None)):
                r.append(f"{f3(dsv(arm, st, 'fid')[ds])} / {f3(dsv(arm, st, 'coverage')[ds])} ({dsv(arm, st, 'n_rules')[ds]:.0f})")
                r.append(f3(dsv(arm, st, "tree_same_size_fid")[ds]))
            rows.append(r)
        parts.append(f"**{A}, dataset-wise** Fid / coverage (boxes) and the same-size tree's Fid\n")
        parts.append(table(["Dataset", "Paper k = 1", "starts 300, τ 0.9, k ∞", "Tree same size", "starts 300, τ 0, k ∞", "Tree same size"], rows))

        # tests at the global end
        st = (300, 0.0, None)
        x = np.array([dsv(arm, st, "fid")[d] for d in DATASETS]); y = np.array([dsv(arm, st, "tree_same_size_fid")[d] for d in DATASETS])
        e = np.array([dsv(arm, st, "eff")[d] for d in DATASETS])
        ok = np.isfinite(x) & np.isfinite(y)
        p1 = paired_wilcoxon(list(x[ok]), list(y[ok]))["pvalue"]
        p2 = paired_wilcoxon(list(e[ok]), list(y[ok]))["pvalue"]
        parts.append(f"At the global end ({A}, starts 300, τ 0, k ∞): Fid on decided rows {x[ok].mean():.3f} vs same-size tree {y[ok].mean():.3f} "
                     f"(RL higher on {(x[ok] > y[ok]).sum()}/{ok.sum()}, p = {p1:.3f}); effectiveness {e[ok].mean():.3f} vs {y[ok].mean():.3f} "
                     f"(RL higher on {(e[ok] > y[ok]).sum()}/{ok.sum()}, p = {p2:.3f}). Unadjusted Wilcoxon over datasets.\n")

    fig = figure(pts, loc, paper, dsv, mean)
    if fig:
        parts.append(f"![Coverage vs fidelity from local to global]({fig.name})\n")
    out = LG / "LOCAL_TO_GLOBAL.md"
    out.write_text("\n".join(parts))
    print(f"wrote {out}")
    return 0


def figure(pts, loc, paper, dsv, mean):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:  # noqa: BLE001
        return None
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.2), sharey=True)
    for ax, arm in zip(axes, ("rlda", "mada")):
        for tau, ls in ((0.9, "-"), (0.0, "--")):
            xs = [mean(dsv(arm, (300, tau, k), "coverage")) for k in (1, 2, 5, 10, 20, 50, None)]
            ys = [mean(dsv(arm, (300, tau, k), "fid")) for k in (1, 2, 5, 10, 20, 50, None)]
            ax.plot(xs, ys, ls, marker="o", color="C0", label=f"{arm.upper()}: starts 300, τ {tau:.1f}, k = 1 … ∞")
        xs = [mean(dsv(arm, (N, 0.0, None), "coverage")) for N in (1, 3, 10, 30, 100, 300)]
        ys = [mean(dsv(arm, (N, 0.0, None), "fid")) for N in (1, 3, 10, 30, 100, 300)]
        ax.plot(xs, ys, ":", marker="s", color="C2", label=f"{arm.upper()}: τ 0, k ∞, starts 1 … 300")
        lp = {m: {q: mean({ds: np.mean([v[q] for v in loc[(arm, ds)][m]]) if loc[(arm, ds)][m] else np.nan for ds in DATASETS})
                  for q in ("emp_fid", "coverage")} for m in ("policy", "anchors", "tree_d3_leaf")}
        ax.scatter([lp["policy"]["coverage"]], [lp["policy"]["emp_fid"]], marker="*", s=160, color="C0", label="policy, one box per input (local)")
        ax.scatter([lp["anchors"]["coverage"]], [lp["anchors"]["emp_fid"]], marker="^", s=70, color="C3", label="Anchors, per input")
        pc = mean({ds: np.mean([p["coverage"] for p in paper[(arm, ds)]]) for ds in DATASETS})
        pf = mean({ds: np.mean([p["fid"] for p in paper[(arm, ds)]]) for ds in DATASETS})
        ax.scatter([pc], [pf], marker="D", s=60, color="C1", label="paper class rule sets (k = 1)")
        tf = mean(dsv(arm, (300, 0.0, None), "tree_same_size_fid"))
        ax.scatter([1.0], [tf], marker="x", s=80, color="k", label="plain tree, same size as global end")
        ax.set_title(arm.upper())
        ax.set_xlabel("coverage (share of D_test rows explained; per input: rows in the box)")
        ax.grid(alpha=0.3)
    axes[0].set_ylabel("empirical fidelity on explained rows")
    axes[1].legend(fontsize=7, loc="lower left")
    fig.tight_layout()
    p = LG / "local_to_global.png"
    fig.savefig(p, dpi=150)
    return p


if __name__ == "__main__":
    raise SystemExit(main())
