"""
Emit paper tables from revision result JSONs. No hand transcription (C-05).

Reads every `rlda_mada_result_v1` file under --results_dir and writes LaTeX.

Usage:
    python paper/make_tables.py --results_dir revision/results --out_dir paper/tables
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from utils.metrics import mean_ci, paired_wilcoxon  # noqa: E402

RANKING_NOTE = (
    r"Ranking score: $\mathrm{fid}\times(1+\mathrm{cov})$ "
    r"(C-52). $k$ is the top-$k$ pool shared by best and union (C-01). "
    r"All metrics on $D_{\mathrm{test}}$; selection on $D_{\mathrm{val}}$ (C-10). "
    r"$\dagger$: $n < $ min\_support$=10$ (C-02). "
    r"Single-seed cells show a Wilson 95\% CI on Fid; multi-seed cells show "
    r"bootstrap mean $\pm$ 95\% CI (C-11)."
)

BASELINE_PREFERENCE = ("anchors", "sp_anchors", "greedy_anchors", "cart")


def _load_results(results_dir: Path) -> List[Dict[str, Any]]:
    rows = []
    for p in sorted(results_dir.glob("*.json")):
        try:
            data = json.loads(p.read_text())
        except Exception:
            continue
        if data.get("schema") != "rlda_mada_result_v1":
            continue
        data["_path"] = str(p)
        rows.append(data)
    return rows


def _fmt(x: Optional[float], digits: int = 3) -> str:
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "—"
    return f"{x:.{digits}f}"


def _fmt_ci(stat: Dict[str, float], digits: int = 3) -> str:
    if not stat or stat.get("n", 0) == 0 or not np.isfinite(stat.get("mean", np.nan)):
        return "—"
    if stat["n"] == 1:
        return _fmt(stat["mean"], digits)
    half = stat["mean"] - stat["ci_low"]
    return f"{stat['mean']:.{digits}f} $\\pm$ {_fmt(half, digits)}"


def _fmt_wilson_or_ci(
    points: List[Optional[float]],
    lo: List[Optional[float]],
    hi: List[Optional[float]],
    digits: int = 3,
) -> str:
    """One seed: point [Wilson]. Multiple seeds: bootstrap mean ± CI."""
    stat = mean_ci(points)
    if stat["n"] == 0:
        return "—"
    if stat["n"] == 1:
        p = stat["mean"]
        wlo = next((x for x in lo if x is not None and np.isfinite(x)), None)
        whi = next((x for x in hi if x is not None and np.isfinite(x)), None)
        if wlo is None or whi is None or not np.isfinite(p):
            return _fmt(p, digits)
        return f"{p:.{digits}f} [{wlo:.{digits}f},{whi:.{digits}f}]"
    return _fmt_ci(stat, digits)


def _dagger(flags: List[bool]) -> str:
    return r"$^\dagger$" if any(flags) else ""


def _n_cell(values: List[Optional[float]], flags: List[bool]) -> str:
    stat = mean_ci(values)
    return _fmt(stat.get("mean"), 1) + _dagger(flags)


def _get(block: Dict[str, Any], *keys: str, default=None):
    cur: Any = block
    for k in keys:
        if not isinstance(cur, dict):
            return default
        cur = cur.get(k)
        if cur is None:
            return default
    return cur


def build_table1(rows: List[Dict[str, Any]]) -> str:
    grouped = defaultdict(list)
    for r in rows:
        for ck, block in (r.get("per_class") or {}).items():
            key = (r["dataset"], r["method"], r["tau_p"], r["tau_c"], ck)
            grouped[key].append(block)

    lines = [
        "% Auto-generated by paper/make_tables.py — do not edit by hand (C-05).",
        f"% {RANKING_NOTE}",
        r"\begin{tabular}{llrrrrrrrrrrr}",
        r"\toprule",
        r"Dataset & Method & Class & $k$ & Fid$_{\mathrm{best}}$ & Pur$_{\mathrm{best}}$ "
        r"& Cov$_{\mathrm{best}}$ & $n_{\mathrm{best}}$ & Fid$_\cup$ & Pur$_\cup$ "
        r"& Cov$_\cup$ & $n_\cup$ & instC \\",
        r"\midrule",
    ]
    last_ds = None
    for key in sorted(grouped.keys()):
        dataset, method, tau_p, tau_c, ck = key
        blocks = grouped[key]
        k = blocks[0].get("k")
        fid_b = _fmt_wilson_or_ci(
            [_get(b, "best", "fidelity", "fidelity") for b in blocks],
            [_get(b, "best", "fidelity", "fidelity_ci_low") for b in blocks],
            [_get(b, "best", "fidelity", "fidelity_ci_high") for b in blocks],
        )
        pur_b = mean_ci([_get(b, "best", "fidelity", "purity") for b in blocks])
        cov_b = mean_ci([_get(b, "best", "fidelity", "coverage") for b in blocks])
        n_b = [_get(b, "best", "fidelity", "n_covered") for b in blocks]
        flag_b = [bool(_get(b, "best", "fidelity", "below_min_support", default=False)) for b in blocks]
        fid_u = _fmt_wilson_or_ci(
            [_get(b, "union", "fidelity") for b in blocks],
            [_get(b, "union", "fidelity_ci_low") for b in blocks],
            [_get(b, "union", "fidelity_ci_high") for b in blocks],
        )
        pur_u = mean_ci([_get(b, "union", "purity") for b in blocks])
        cov_u = mean_ci([_get(b, "union", "coverage") for b in blocks])
        n_u = [_get(b, "union", "n_covered") for b in blocks]
        flag_u = [bool(_get(b, "union", "below_min_support", default=False)) for b in blocks]
        inst_c = mean_ci([_get(b, "instance", "coverage") for b in blocks])
        cls = ck.replace("class_", "")
        ds_cell = dataset if dataset != last_ds else ""
        last_ds = dataset
        lines.append(
            f"{ds_cell} & {method} & {cls} & {k} & "
            f"{fid_b} & {_fmt_ci(pur_b)} & {_fmt_ci(cov_b)} & {_n_cell(n_b, flag_b)} & "
            f"{fid_u} & {_fmt_ci(pur_u)} & {_fmt_ci(cov_u)} & {_n_cell(n_u, flag_u)} & "
            f"{_fmt_ci(inst_c)} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def assert_anchors_identical_across_tau_c(rows: List[Dict[str, Any]]) -> None:
    """C-05 action 3: Anchors baseline must be byte-identical across tau_C tables."""
    by_key = defaultdict(list)
    for r in rows:
        if r.get("method") not in ("anchors", "sp_anchors", "greedy_anchors"):
            continue
        key = (r["dataset"], r["method"], r["seed"], r["tau_p"])
        payload = json.dumps(r.get("per_class"), sort_keys=True, default=str)
        by_key[key].append((r["tau_c"], payload, r.get("_path")))
    for key, items in by_key.items():
        payloads = {p for _, p, _ in items}
        if len(payloads) > 1:
            paths = [path for _, _, path in items]
            raise AssertionError(
                f"Anchors baseline differs across tau_C for {key}. "
                f"It must not (Anchors does not depend on tau_C). Files: {paths}"
            )


def build_global_table(rows: List[Dict[str, Any]]) -> str:
    grouped = defaultdict(list)
    for r in rows:
        g = r.get("global_ruleset") or {}
        grouped[(r["dataset"], r["method"], r["tau_p"], r["tau_c"])].append(g)
    lines = [
        "% Auto-generated global rule-set table (C-14).",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Dataset & Method & Global Fid & Abstention & Conflict & Coverage \\",
        r"\midrule",
    ]
    for key in sorted(grouped.keys()):
        dataset, method, tau_p, tau_c = key
        gs = grouped[key]
        fid = mean_ci([g.get("global_fidelity") for g in gs])
        abs_ = mean_ci([g.get("abstention_rate") for g in gs])
        conf = mean_ci([g.get("conflict_rate") for g in gs])
        cov = mean_ci([g.get("coverage") for g in gs])
        lines.append(
            f"{dataset} & {method} & {_fmt_ci(fid)} & {_fmt_ci(abs_)} & {_fmt_ci(conf)} & {_fmt_ci(cov)} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def build_classifier_table(rows: List[Dict[str, Any]]) -> str:
    grouped = defaultdict(list)
    for r in rows:
        grouped[(r["dataset"], r["method"], r["seed"])].append(r.get("classifier_accuracy") or {})
    lines = [
        "% Classifier train/val/test accuracy (C-09 / C-24).",
        r"\begin{tabular}{llrrr}",
        r"\toprule",
        r"Dataset & Method & Train acc. & Val acc. & Test acc. \\",
        r"\midrule",
    ]
    seen = set()
    for dataset, method, seed in sorted(grouped.keys()):
        key = (dataset, method)
        if key in seen:
            continue
        seen.add(key)
        accs = grouped[(dataset, method, seed)]
        # Prefer first seed; mean_ci if multiple files share method/dataset
        all_acc = []
        for r in rows:
            if r["dataset"] == dataset and r["method"] == method:
                all_acc.append(r.get("classifier_accuracy") or {})
        tr = mean_ci([a.get("train_accuracy") for a in all_acc])
        va = mean_ci([a.get("val_accuracy") for a in all_acc])
        te = mean_ci([a.get("test_accuracy") for a in all_acc])
        n_test = next((a.get("n") for a in all_acc if a.get("n") is not None), None)
        n_note = f" ($n={n_test}$)" if n_test is not None else ""
        lines.append(
            f"{dataset} & {method} & {_fmt_ci(tr)} & {_fmt_ci(va)} & {_fmt_ci(te)}{n_note} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def build_queries_table(rows: List[Dict[str, Any]]) -> str:
    grouped = defaultdict(list)
    for r in rows:
        grouped[(r["dataset"], r["method"])].append(r.get("queries") or {})
    lines = [
        "% Query budget / wall-clock (C-12). Generation queries exclude held-out reporting.",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Dataset & Method & Black-box queries & Reporting queries & Train s & Infer s \\",
        r"\midrule",
    ]
    for key in sorted(grouped.keys()):
        dataset, method = key
        qs = grouped[key]
        nq = mean_ci([q.get("n_blackbox_queries") for q in qs])
        nr = mean_ci([q.get("n_reporting_queries") for q in qs])
        wt = mean_ci([q.get("wall_train_seconds") for q in qs])
        wi = mean_ci([q.get("wall_infer_seconds") for q in qs])
        lines.append(
            f"{dataset} & {method} & {_fmt_ci(nq, 0)} & {_fmt_ci(nr, 0)} & "
            f"{_fmt_ci(wt, 2)} & {_fmt_ci(wi, 2)} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def build_success_table(rows: List[Dict[str, Any]]) -> str:
    grouped = defaultdict(list)
    for r in rows:
        grouped[(r["dataset"], r["method"], r["tau_p"], r["tau_c"])].append(
            r.get("success_rate") or {}
        )
    lines = [
        r"% Success rate: fraction of instance episodes reaching $\tau_P$ and $\tau_C$ (C-11).",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Dataset & Method & $\tau_P$ & $\tau_C$ & $n$ episodes & Success rate \\",
        r"\midrule",
    ]
    n_rows = 0
    for key in sorted(grouped.keys()):
        dataset, method, tau_p, tau_c = key
        ss = grouped[key]
        if all(s.get("n_episodes") in (None, 0) and s.get("success_rate") is None for s in ss):
            continue
        n_ep = mean_ci([s.get("n_episodes") for s in ss])
        rate = mean_ci([s.get("success_rate") for s in ss])
        lines.append(
            f"{dataset} & {method} & {_fmt(tau_p, 2)} & {_fmt(tau_c, 2)} & "
            f"{_fmt(n_ep.get('mean'), 0)} & {_fmt_ci(rate)} \\\\"
        )
        n_rows += 1
    if n_rows == 0:
        lines.append(
            r"\multicolumn{6}{l}{No success-rate records (baselines without episodes).} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def build_compactness_table(rows: List[Dict[str, Any]]) -> str:
    grouped = defaultdict(list)
    for r in rows:
        grouped[(r["dataset"], r["method"])].append(r.get("compactness") or {})
    lines = [
        "% Active features per selected rule (C-36 / C-08). Threshold = sparsity_width_ratio.",
        r"\begin{tabular}{llrrr}",
        r"\toprule",
        r"Dataset & Method & Rules / class & Mean active features & Sparsity ratio \\",
        r"\midrule",
    ]
    for key in sorted(grouped.keys()):
        dataset, method = key
        cs = grouped[key]
        nr = mean_ci([c.get("mean_rules_per_class") for c in cs])
        na = mean_ci([c.get("mean_active_features") for c in cs])
        sp = next((c.get("sparsity_width_ratio") for c in cs if c.get("sparsity_width_ratio") is not None), None)
        lines.append(
            f"{dataset} & {method} & {_fmt_ci(nr, 1)} & {_fmt_ci(na, 2)} & {_fmt(sp, 2)} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def _pick_baseline(methods: List[str]) -> Optional[str]:
    for name in BASELINE_PREFERENCE:
        if name in methods:
            return name
    return None


def build_wilcoxon_table(rows: List[Dict[str, Any]]) -> str:
    """Paired Wilcoxon vs the first available baseline, matched on (dataset, class, seed)."""
    by_key: Dict[Tuple, Dict[str, float]] = defaultdict(dict)
    methods = sorted({r["method"] for r in rows})
    baseline = _pick_baseline(methods)
    lines = [
        "% Paired Wilcoxon signed-rank vs class-level baseline on Fid$_\\cup$ (C-11 / C-26).",
        f"% Baseline method: {baseline or 'NONE — add SP-Anchors / greedy Anchors / CART rows'}.",
    ]
    if baseline is None:
        lines += [
            r"\begin{tabular}{l}",
            r"\toprule",
            r"No class-level baseline result files; Wilcoxon not computed. \\",
            r"\bottomrule",
            r"\end{tabular}",
        ]
        return "\n".join(lines) + "\n"

    for r in rows:
        for ck, block in (r.get("per_class") or {}).items():
            fid = _get(block, "union", "fidelity")
            if fid is None:
                continue
            key = (r["dataset"], r["tau_p"], r["tau_c"], ck, r["seed"])
            by_key[key][r["method"]] = float(fid)

    # Pair per (dataset, class) across seeds — not across classes on one seed.
    pairs = defaultdict(lambda: {"a": [], "b": []})
    for key, mfid in by_key.items():
        if baseline not in mfid:
            continue
        dataset, tau_p, tau_c, ck, seed = key
        for method, val in mfid.items():
            if method == baseline:
                continue
            pairs[(dataset, method, ck)]["a"].append(val)
            pairs[(dataset, method, ck)]["b"].append(mfid[baseline])

    # Collapse classes into one test per (dataset, method) only when every class
    # has ≥2 seeds; otherwise report per-class n and refuse a p-value.
    collapsed = defaultdict(lambda: {"a": [], "b": [], "n_class_cells": 0, "min_n": 10**9})
    for (dataset, method, ck), ab in pairs.items():
        n = len(ab["a"])
        collapsed[(dataset, method)]["a"].extend(ab["a"])
        collapsed[(dataset, method)]["b"].extend(ab["b"])
        collapsed[(dataset, method)]["n_class_cells"] += 1
        collapsed[(dataset, method)]["min_n"] = min(collapsed[(dataset, method)]["min_n"], n)

    lines += [
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        rf"Dataset & Method vs {baseline} & $n$ pairs & $p$ & Rank-biserial $r$ & Mean $\Delta$ Fid$_\cup$ \\",
        r"\midrule",
    ]
    n_emitted = 0
    for (dataset, method) in sorted(collapsed.keys()):
        rec = collapsed[(dataset, method)]
        n_seeds = rec["min_n"]
        if n_seeds < 2:
            md = None
            if rec["a"]:
                md = float(np.mean(np.asarray(rec["a"]) - np.asarray(rec["b"])))
            lines.append(
                f"{dataset} & {method} & {n_seeds} & too few seeds "
                r"(need $\geq$ 2) & — & " + f"{_fmt(md)} \\\\"
            )
        else:
            res = paired_wilcoxon(rec["a"], rec["b"])
            n = res.get("n") or 0
            p = res.get("pvalue")
            r_rb = res.get("effect_size_rank_biserial")
            md = res.get("mean_diff")
            lines.append(
                f"{dataset} & {method} & {n} & {_fmt(p, 4)} & {_fmt(r_rb)} & {_fmt(md)} \\\\"
            )
        n_emitted += 1
    if n_emitted == 0:
        lines.append(
            rf"\multicolumn{{6}}{{l}}{{No matched (dataset, class, seed) pairs against {baseline}.}} \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def build_notes(rows: List[Dict[str, Any]]) -> str:
    formulas = sorted({
        r.get("ranking_formula") or (r.get("extra") or {}).get("ranking_formula")
        for r in rows
        if r.get("ranking_formula") or (r.get("extra") or {}).get("ranking_formula")
    })
    supports = sorted({
        r.get("min_support") or (r.get("extra") or {}).get("min_support")
        for r in rows
        if r.get("min_support") or (r.get("extra") or {}).get("min_support")
    })
    splits = []
    for r in rows:
        ss = (r.get("extra") or {}).get("split_sizes") or {}
        if ss:
            splits.append(
                f"{r['dataset']}: train={ss.get('train')} val={ss.get('val')} test={ss.get('test')}"
            )
    split_u = sorted(set(splits))
    seeds = sorted({int(r["seed"]) for r in rows})
    methods = sorted({r["method"] for r in rows})
    return "\n".join([
        "% Reporting notes (C-02, C-10, C-51, C-52).",
        f"% ranking_formula: {formulas or ['precision_coverage']}",
        f"% min_support: {supports or [10]}",
        f"% seeds: {seeds}",
        f"% methods: {methods}",
        f"% splits: {split_u}",
        RANKING_NOTE,
        "",
    ])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results_dir", default="revision/results")
    ap.add_argument("--out_dir", default="paper/tables")
    args = ap.parse_args()
    results_dir = Path(args.results_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = _load_results(results_dir)
    if not rows:
        print(f"No rlda_mada_result_v1 files in {results_dir}")
        return
    assert_anchors_identical_across_tau_c(rows)
    writers = {
        "table_main.tex": build_table1,
        "table_global.tex": build_global_table,
        "table_classifier.tex": build_classifier_table,
        "table_queries.tex": build_queries_table,
        "table_success.tex": build_success_table,
        "table_compactness.tex": build_compactness_table,
        "table_wilcoxon.tex": build_wilcoxon_table,
    }
    for name, fn in writers.items():
        (out_dir / name).write_text(fn(rows))
    (out_dir / "table_notes.tex").write_text(build_notes(rows))
    print(f"Wrote {len(writers) + 1} tables in {out_dir} from {len(rows)} result files")


if __name__ == "__main__":
    main()
